version: '3.1'

services:
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD : root
      MYSQL_DATABASE: niagahoster
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - 6033:3306

  niagahosterapp:
    build: ./niagahosterapp
    volumes: 
      - ./niagahosterapp:/var/www/html/
    depends_on:
       - db
    restart: always
    # links:
    #   - db:mysql
    ports:
      - "8004:80"

volumes:
    db_data:
